apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: insurance
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/insurance"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"