apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: insurance
type: Opaque
data:
  username: aW5zdXJhbmNlX3VzZXI=   # insurance_user
  password: aW5zdXJhbmNlX3Bhc3M=   # insurance_pass