apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-api
  namespace: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance-api
  template:
    metadata:
      labels:
        app: insurance-api
    spec:
      containers:
        - name: insurance-api
          image: thecheddarmonster/insurance-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: dockerhub-secret